export enum DrugAlternativeMatchType {
  EXACT_COMPOSITION = 'EXACT_COMPOSITION',
  SAME_INGREDIENTS_DIFFERENT_STRENGTH = 'SAME_INGREDIENTS_DIFFERENT_STRENGTH',
  SAME_INGREDIENTS_DIFFERENT_FORM = 'SAME_INGREDIENTS_DIFFERENT_FORM',
}
